python demo.py ctdet \
        --dataset table \
        --demo ./dir_of_input_images/ \
        --demo_name demo_on_wtw \
        --dataset_name WTW \
        --debug 1 \
        --arch dla_34 \
        --K 3000 \
        --MK 5000 \
        --tsfm_layers 4 \
        --stacking_layers 4 \
        --gpus 0\
        --wiz_4ps \
        --wiz_detect \
        --wiz_rev \
        --wiz_stacking \
        --convert_onnx 0 \
        --vis_thresh_corner 0.3 \
        --vis_thresh 0.20 \
        --scores_thresh 0.2 \
        --nms \
        --demo_dir ./dir_of_visualization/ \
        --anno_path ./dir_of_annotations/json/test.json \ #optional when the input image set contains only test images
        --load_model ./dir_of_pretrained/model_best.pth \
        --load_processor ./dir_of_pretrained/processor_best.pth 
