python main.py ctdet \
	--dataset_name table \
	--exp_id training_wtw \
	--dataset_name WTW \
	--image_dir ./dir_of_images \
	--wiz_4ps \
	--wiz_stacking \
	--wiz_pairloss \
	--tsfm_layers 3 \
	--stacking_layers 3 \
	--batch_size 32 \
	--master_batch 6 \
	--arch dla_34 \
	--lr 1e-4 \
	--K 500 \
	--MK 1000 \
	--num_epochs 100 \
	--lr_step '70, 90' \
	--gpus 0,1,2,3 \
	--num_workers 16 \
	--val_intervals 10 