python main.py ctdet_small \
	--dataset table_small \
	--exp_id training_ptn \
	--dataset_name PTN \
	--image_dir ./dir_of_images \
	--wiz_2dpe \
    --wiz_stacking \
	--tsfm_layers 3 \
	--stacking_layers 3 \
	--batch_size 128 \
	--master_batch 20 \
	--arch dla_34 \
	--lr 1e-4 \
	--K 500 \
	--MK 1000 \
	--num_epochs 100 \
	--lr_step '70, 90' \
	--gpus 0,1,2,3\
	--num_workers 16 \
	--val_intervals 10 \
	--load_model ./dir_of_pretrained/model_best.pth \
	--load_processor ./dir_of_pretrained/processor_best.pth 